pipeline {
    agent any

    stages {
        stage('test') {
            steps {
                sh "mvn clean compile test"
            }
        }
        stage('Build') {
            steps {
                sh "mvn clean package"
            }
            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
